name: CI/CD Pipeline

on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'

      - name: Build with Maven
        run: mvn -B package --file /Inversion-api/pom.xml

      - name: Build Docker image
        run: docker build -t inversion-api .

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'sua_regiao_aws'

      - name: Provision Infrastructure with Terraform
        run: |
          cd ./path/to/your/terraform/directory
          terraform init
          terraform apply -auto-approve

      - name: Deploy Docker container
        run: |
          docker run -d --name seu-container -p 8080:8080 inversion-api

      - name: Test the application
        run: docker exec -it seu-container mvn test

      - name: Notify on Slack or other channels
        # Add a step here to send notifications about the pipeline status.
        # You might use a Slack action or a custom script.

